[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit AHTX0
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit BusIO
  marcoschwartz/LiquidCrystal_I2C